# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardType', models.CharField(max_length=250)),
                ('OrgName', models.CharField(max_length=200)),
                ('HolderName', models.CharField(max_length=250)),
                ('PlaceLost', models.CharField(max_length=250)),
                ('User', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
