# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='User',
        ),
    ]
