# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0005_auto_20170130_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='card',
        ),
        migrations.DeleteModel(
            name='New',
        ),
    ]
