# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0006_auto_20170130_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=250)),
                ('holder', models.CharField(max_length=250)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LostCard.Card')),
            ],
        ),
    ]
