# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0007_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
