# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0009_auto_20170206_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specs',
            old_name='cards',
            new_name='card',
        ),
    ]
