# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0011_auto_20170324_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='specs',
            name='email_add',
            field=models.EmailField(default='eee@example.com', max_length=80),
            preserve_default=False,
        ),
    ]
