# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0012_specs_email_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='value',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
    ]
