# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0013_card_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardType', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Specs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Org_Name', models.CharField(max_length=200)),
                ('holder_name', models.CharField(max_length=250)),
                ('id_card', models.CharField(max_length=100)),
                ('email_add_founder', models.EmailField(max_length=80)),
                ('phone_no', models.CharField(max_length=20)),
                ('card2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LostCard.Card2')),
            ],
        ),
    ]
