# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0014_card2_specs2'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='fa',
            field=models.CharField(default='zx', max_length=28),
            preserve_default=False,
        ),
    ]
