# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0015_card_fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='fa',
        ),
    ]
