# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0016_remove_card_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_img',
            field=models.FileField(default='S', upload_to=''),
            preserve_default=False,
        ),
    ]
