# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0017_card_card_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card2',
            new_name='CardFound',
        ),
        migrations.RenameModel(
            old_name='Specs2',
            new_name='SpecsFound',
        ),
    ]
