# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0018_auto_20170324_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='specsfound',
            name='card_img',
            field=models.FileField(default='s', upload_to=''),
            preserve_default=False,
        ),
    ]
