# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LostCard', '0019_specsfound_card_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specsfound',
            name='card_img',
        ),
        migrations.AddField(
            model_name='cardfound',
            name='card_img',
            field=models.FileField(default='s', upload_to=''),
            preserve_default=False,
        ),
    ]
